### ISSUE TITLE
Changing deviceSize() to static let deviceSize

### ISSUE THREAD

**Issue by purpleblues** [cruisediary/DeviceLayout#15]
How about changing

```swift
 open func deviceSize() -> Size {
    return Device.size()
 }
```

to

```swift
public static let deviceSize = Device.size()
```

So you can use deviceSize like this

```swift
if size == DeviceLayoutConstraint.deviceSize {
    self.constant = constant
    layoutIfNeeded()
}

```

This change might boost up performance little bit.

**Comment by cruisediary** [comment]
Thank you for opening issue on DeviceLayout

I'm use `func deviceSize()` as Dependeny Injection for Unittest

in mock object, can test autolayout constant really set correct constant per device

so something to need for Unittest injecting `Size`

I agree that use `static let variable DeviceSize` for performance

because current `func deviceSize()` always calculate `Device.size()` in every constraint 

it's good to use like singleton (device size never change)

if use `public static let deviceSize = Device.size()` can not test Unittest

alternative solution is use `static var` than `static let` but it's not good solution I think

Perspective in OOP, `class Device` have a responsibility for having static size of Device (once allocated or assigned) than `DeviceLayoutConstraint` if possible

how about use like below? :)

```swift
    //Mark: Add static let inside Static struct because func deviceSize() cause naming redeclation
    private struct Static {
        static let deviceSize: Size = Device.size()
    }

    open func deviceSize() -> Size {
        return Static.deviceSize
    }

    //Mark: unittest mock object it can test constant per expectedDevice
    class DeviceLayoutConstraintSpy: DeviceLayoutConstraint {
        var expectedDeviceSize: Size!
        
        override open func deviceSize() -> Size {
            return expectedDeviceSize
        }
    }
```

**Comment by cruisediary** [comment]
reflected in #16 thank you :)
